[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "biopython>=1.86",
    "celery==5.5.0",
    "eventlet==0.39.1",
    "flask==2.3.3",
    "flask-cors==5.0.1",
    "flask-socketio==5.3.6",
    "gunicorn>=25.1.0",
    "minknow-api==6.2.1",
    "numpy==1.26.4",
    "pysam==0.23.0",
    "python-dotenv>=1.2.2",
    "redis==5.2.1",
    "twilio>=9.10.3",
    "watchdog==6.0.0",
]
